"""Add missing StudyRoom created_by

Revision ID: 134167a9059f
Revises: f5fdfa051eb7
Create Date: 2026-02-15 02:59:26.213699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134167a9059f'
down_revision: Union[str, Sequence[str], None] = 'f5fdfa051eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_rooms', sa.Column('created_by', sa.String(), nullable=False))
    op.create_foreign_key(None, 'study_rooms', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_rooms', type_='foreignkey')
    op.drop_column('study_rooms', 'created_by')
    # ### end Alembic commands ###
