"""Add materials report model

Revision ID: 2eba57c88242
Revises: 5829c8c8134f
Create Date: 2026-02-15 16:07:03.683668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eba57c88242'
down_revision: Union[str, Sequence[str], None] = '5829c8c8134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_material_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['study_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_material_reports')
    # ### end Alembic commands ###
