"""Change field type User

Revision ID: 591c481fb72d
Revises: e52f1549c9c2
Create Date: 2026-02-14 16:56:09.584670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591c481fb72d'
down_revision: Union[str, Sequence[str], None] = 'e52f1549c9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'is_active',
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        postgresql_using="is_active::boolean",
        existing_nullable=True,
    )
    op.alter_column(
        'users',
        'is_superuser',
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        postgresql_using="is_superuser::boolean",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'is_superuser',
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        postgresql_using="is_superuser::varchar",
        existing_nullable=True,
    )
    op.alter_column(
        'users',
        'is_active',
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        postgresql_using="is_active::varchar",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
