"""Add indexes

Revision ID: 7a14f44cb12f
Revises: 526868f6590e
Create Date: 2026-02-15 18:58:25.719845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a14f44cb12f'
down_revision: Union[str, Sequence[str], None] = '526868f6590e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_study_material_reports_material_id'), 'study_material_reports', ['material_id'], unique=False)
    op.create_index(op.f('ix_study_material_reports_reported_by'), 'study_material_reports', ['reported_by'], unique=False)
    op.create_index(op.f('ix_study_materials_room_id'), 'study_materials', ['room_id'], unique=False)
    op.create_index(op.f('ix_study_materials_uploaded_by'), 'study_materials', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_study_rooms_created_by'), 'study_rooms', ['created_by'], unique=False)
    op.create_index(op.f('ix_study_rooms_name'), 'study_rooms', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_rooms_name'), table_name='study_rooms')
    op.drop_index(op.f('ix_study_rooms_created_by'), table_name='study_rooms')
    op.drop_index(op.f('ix_study_materials_uploaded_by'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_room_id'), table_name='study_materials')
    op.drop_index(op.f('ix_study_material_reports_reported_by'), table_name='study_material_reports')
    op.drop_index(op.f('ix_study_material_reports_material_id'), table_name='study_material_reports')
    # ### end Alembic commands ###
