"""Fix timestamp issues

Revision ID: a3631c7ffd26
Revises: b8a5f3d2e065
Create Date: 2026-02-15 03:07:51.504766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3631c7ffd26'
down_revision: Union[str, Sequence[str], None] = 'b8a5f3d2e065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    UPDATE study_rooms
    SET updated_at = created_at
    WHERE updated_at IS NULL
    """)
    # Ensure the database assigns a default timestamp for new rows
    op.alter_column(
        'study_rooms',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text('now()'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the server default when downgrading and allow nulls again
    op.alter_column(
        'study_rooms',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        server_default=None,
    )
    # ### end Alembic commands ###
