"""Add superuser to User model

Revision ID: e52f1549c9c2
Revises: 9fe7b9a557c2
Create Date: 2026-02-14 15:27:47.799695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52f1549c9c2'
down_revision: Union[str, Sequence[str], None] = '9fe7b9a557c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
