"""Fix timestamp issues

Revision ID: ec6ad0007657
Revises: 134167a9059f
Create Date: 2026-02-15 03:03:41.717525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec6ad0007657'
down_revision: Union[str, Sequence[str], None] = '134167a9059f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # backfill any NULL updated_at values with created_at so NOT NULL constraint can be applied
    op.execute("""
    UPDATE study_rooms
    SET updated_at = created_at
    WHERE updated_at IS NULL
    """)

    op.alter_column('study_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
